# Generated by Django 4.0.4 on 2022-04-14 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiMailer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mail',
            name='start',
            field=models.DateTimeField(verbose_name='Дата и время начала рассылки'),
        ),
    ]
